# Uncomment this line to define a global platform for your project
# platform :ios, ’10.0’

target 'NASApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NASApp
	pod 'Nuke', '~> 5.0'

end
